version: 2
jobs:
  build:
    docker:
      - image: ruby:2
    steps:
      - checkout
      - run: gem install bundler --no-doc
      - run: bundle install --path vendor/bundle
      - run: bundle exec jekyll build
